#!/usr/bin/env node
/**
 * Build the dock's client assets into one importable module.
 *
 * `src/client.ts` is bundled (IIFE, readable — no minify) and `src/styles.css`
 * is read verbatim; both are written into `src/assets.gen.ts` as exported
 * string constants. The server-side renderer imports that module, so:
 *
 *   - `tsc -b` needs no special loaders — the assets are ordinary TS;
 *   - `scripts/bundle.mjs` inlines them into `dist/agent2llm.mjs`, which is
 *     how compiled assets ship in the npm package with no extra pack steps;
 *   - the served page stays a single self-contained document: no CDN, no
 *     external stylesheet, no external script.
 */
import { build } from "esbuild";
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));

const result = await build({
  entryPoints: [join(HERE, "src", "client.ts")],
  bundle: true,
  format: "iife",
  globalName: "__a2l_dock",
  target: "es2020",
  minify: false,
  write: false,
  logLevel: "info",
});

const js = result.outputFiles[0].text;
const css = readFileSync(join(HERE, "src", "styles.css"), "utf8");

// The generated module is inlined inside a <script> element by the renderer.
// A literal closing tag anywhere in the bundle would end that element early —
// the same trap the token literal's guard covers. Fail the build instead of
// shipping an XSS-shaped artifact.
if (/<\/script/i.test(js) || /<\/script/i.test(css)) {
  throw new Error("client asset contains a literal closing script tag; split it before inlining");
}

const header =
  "// Generated by apps/dock/build.mjs from src/client.ts and src/styles.css — DO NOT EDIT.\n" +
  "// Regenerate with: npm run build:dock\n\n";

writeFileSync(
  join(HERE, "src", "assets.gen.ts"),
  header + `export const DOCK_CSS = ${JSON.stringify(css)};\n\nexport const DOCK_JS = ${JSON.stringify(js)};\n`
);

console.log("apps/dock: assets.gen.ts written");
